# Generated by Django 5.2 on 2025-04-05 16:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('usuarios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PeriodoVacacional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio_periodo', models.DateField()),
                ('fecha_fin_periodo', models.DateField()),
                ('dias_totales_periodo', models.IntegerField()),
                ('dias_pendientes_periodo', models.IntegerField()),
                ('dias_disfrutados_periodo', models.IntegerField(default=0)),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.funcionario')),
            ],
        ),
        migrations.CreateModel(
            name='SolicitudVacaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_sabs', models.CharField(max_length=50, unique=True)),
                ('fecha_elaboracion', models.DateField(auto_now_add=True)),
                ('fecha_inicio_vacaciones', models.DateField()),
                ('fecha_fin_vacaciones', models.DateField()),
                ('total_dias_solicitados', models.IntegerField()),
                ('tipo_dias_solicitados', models.CharField(choices=[('H', 'Hábiles'), ('C', 'Calendario')], max_length=1)),
                ('quincena_pago', models.IntegerField(choices=[(1, 'Primera'), (2, 'Segunda')])),
                ('mes_pago', models.IntegerField()),
                ('anio_pago', models.IntegerField()),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('disfrute_dias_pendientes', models.BooleanField(default=False)),
                ('estado_solicitud', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes_estado', to='core.catalogo')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.funcionario')),
                ('periodo_vacacional', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vacaciones.periodovacacional')),
            ],
        ),
        migrations.CreateModel(
            name='ReintegroVacaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_sabs', models.CharField(max_length=50, unique=True)),
                ('fecha_elaboracion', models.DateField(auto_now_add=True)),
                ('fecha_reintegro', models.DateField()),
                ('motivo_reintegro', models.CharField(choices=[('Vacaciones', 'Vacaciones')], max_length=50)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_disfrute_desde', models.DateField()),
                ('fecha_disfrute_hasta', models.DateField()),
                ('dias_disfrutados', models.IntegerField()),
                ('tipo_dias_disfrutados', models.CharField(choices=[('H', 'Hábiles'), ('C', 'Calendario')], max_length=1)),
                ('dias_pendientes', models.IntegerField()),
                ('tipo_dias_pendientes', models.CharField(choices=[('H', 'Hábiles'), ('C', 'Calendario')], max_length=1)),
                ('estado_solicitud', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reintegros_estado', to='core.catalogo')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.funcionario')),
                ('periodo_vacacional', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vacaciones.periodovacacional')),
                ('solicitud_vacaciones', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vacaciones.solicitudvacaciones')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricoAcciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion_realizada', models.CharField(max_length=50)),
                ('fecha_hora_accion', models.DateTimeField(auto_now_add=True)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('tipo_accion', models.CharField(choices=[('solicitud', 'Solicitud'), ('reintegro', 'Reintegro')], max_length=20)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('reintegro_vacaciones', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vacaciones.reintegrovacaciones')),
                ('solicitud_vacaciones', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vacaciones.solicitudvacaciones')),
            ],
        ),
        migrations.CreateModel(
            name='DiasPendientesVacaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo_desde', models.IntegerField()),
                ('periodo_hasta', models.IntegerField()),
                ('dias_a_disfrutar', models.IntegerField()),
                ('dias_pendientes', models.IntegerField()),
                ('fecha_disfrute_desde', models.DateField()),
                ('fecha_disfrute_hasta', models.DateField()),
                ('solicitud_vacaciones', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacaciones.solicitudvacaciones')),
            ],
        ),
    ]
