# Generated by Django 5.2 on 2025-04-16 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacaciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diaspendientesvacaciones',
            options={'verbose_name': 'Días pendientes de vacaciones', 'verbose_name_plural': 'Días pendientes de vacaciones'},
        ),
        migrations.AlterModelOptions(
            name='historicoacciones',
            options={'verbose_name': 'Historial de acciones', 'verbose_name_plural': 'Historial de acciones'},
        ),
        migrations.AlterModelOptions(
            name='periodovacacional',
            options={'verbose_name': 'Periodo vacacional', 'verbose_name_plural': 'Periodos vacacionales'},
        ),
        migrations.AlterModelOptions(
            name='reintegrovacaciones',
            options={'verbose_name': 'Reintegro de vacaciones', 'verbose_name_plural': 'Reintegros de vacaciones'},
        ),
        migrations.AlterModelOptions(
            name='solicitudvacaciones',
            options={'verbose_name': 'Solicitud de vacaciones', 'verbose_name_plural': 'Solicitudes de vacaciones'},
        ),
        migrations.DeleteModel(
            name='Notificacion',
        ),
    ]
