# Generated by Django 5.2 on 2025-04-17 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacaciones', '0002_alter_diaspendientesvacaciones_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reintegrovacaciones',
            options={'permissions': [('dar_visto_bueno_reintegro', 'Puede dar visto bueno a reintegros de vacaciones'), ('devolver_reintegro', 'Puede devolver reintegros de vacaciones para corrección'), ('autorizar_reintegro', 'Puede autorizar reintegros de vacaciones'), ('rechazar_reintegro', 'Puede rechazar reintegros de vacaciones'), ('cerrar_reintegro', 'Puede cerrar reintegros de vacaciones'), ('crear_reintegro_vacaciones', 'Puede crear reintegros de vacaciones'), ('editar_reintegro_vacaciones', 'Puede editar reintegros de vacaciones'), ('ver_reintegro_vacaciones', 'Puede ver reintegros de vacaciones')], 'verbose_name': 'Reintegro de vacaciones', 'verbose_name_plural': 'Reintegros de vacaciones'},
        ),
        migrations.AlterModelOptions(
            name='solicitudvacaciones',
            options={'permissions': [('dar_visto_bueno_solicitud', 'Puede dar visto bueno a solicitudes de vacaciones'), ('devolver_solicitud', 'Puede devolver solicitudes de vacaciones para corrección'), ('autorizar_solicitud', 'Puede autorizar solicitudes de vacaciones'), ('rechazar_solicitud', 'Puede rechazar solicitudes de vacaciones'), ('cerrar_solicitud', 'Puede cerrar solicitudes de vacaciones'), ('crear_solicitud_vacaciones', 'Puede crear solicitudes de vacaciones'), ('editar_solicitud_vacaciones', 'Puede editar solicitudes de vacaciones'), ('ver_solicitud_vacaciones', 'Puede ver solicitudes de vacaciones')], 'verbose_name': 'Solicitud de vacaciones', 'verbose_name_plural': 'Solicitudes de vacaciones'},
        ),
    ]
