# Generated by Django 5.2 on 2025-04-22 05:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_remove_customuser_first_name_and_more'),
        ('vacaciones', '0003_alter_reintegrovacaciones_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='periodovacacional',
            options={'ordering': ['-fecha_inicio_periodo'], 'verbose_name': 'Periodo vacacional', 'verbose_name_plural': 'Periodos vacacionales'},
        ),
        migrations.AlterModelOptions(
            name='reintegrovacaciones',
            options={'permissions': [('crear_reintegro_vacaciones', 'Puede crear reintegros de vacaciones'), ('editar_reintegro_vacaciones', 'Puede editar reintegros de vacaciones'), ('ver_reintegro_vacaciones', 'Puede ver reintegros de vacaciones'), ('dar_visto_bueno_reintegro', 'Puede dar visto bueno a reintegros de vacaciones'), ('devolver_reintegro', 'Puede devolver reintegros para corrección'), ('autorizar_reintegro', 'Puede autorizar reintegros de vacaciones'), ('rechazar_reintegro', 'Puede rechazar reintegros de vacaciones'), ('cerrar_reintegro', 'Puede cerrar reintegros de vacaciones')], 'verbose_name': 'Reintegro de vacaciones', 'verbose_name_plural': 'Reintegros de vacaciones'},
        ),
        migrations.AlterModelOptions(
            name='solicitudvacaciones',
            options={'permissions': [('crear_solicitud_vacaciones', 'Puede crear solicitudes de vacaciones'), ('editar_solicitud_vacaciones', 'Puede editar solicitudes de vacaciones'), ('ver_solicitud_vacaciones', 'Puede ver solicitudes de vacaciones'), ('dar_visto_bueno_solicitud', 'Puede dar visto bueno a solicitudes de vacaciones'), ('devolver_solicitud', 'Puede devolver solicitudes de vacaciones para corrección'), ('autorizar_solicitud', 'Puede autorizar solicitudes de vacaciones'), ('rechazar_solicitud', 'Puede rechazar solicitudes de vacaciones'), ('cerrar_solicitud', 'Puede cerrar solicitudes de vacaciones')], 'verbose_name': 'Solicitud de vacaciones', 'verbose_name_plural': 'Solicitudes de vacaciones'},
        ),
        migrations.AlterField(
            model_name='periodovacacional',
            name='dias_disfrutados_periodo',
            field=models.IntegerField(default=0, verbose_name='Días disfrutados del periodo'),
        ),
        migrations.AlterField(
            model_name='periodovacacional',
            name='dias_pendientes_periodo',
            field=models.IntegerField(verbose_name='Días pendientes del periodo'),
        ),
        migrations.AlterField(
            model_name='periodovacacional',
            name='dias_totales_periodo',
            field=models.IntegerField(verbose_name='Días totales del periodo'),
        ),
        migrations.AlterField(
            model_name='periodovacacional',
            name='fecha_fin_periodo',
            field=models.DateField(verbose_name='Fecha de fin del periodo'),
        ),
        migrations.AlterField(
            model_name='periodovacacional',
            name='fecha_inicio_periodo',
            field=models.DateField(verbose_name='Fecha de inicio del periodo'),
        ),
        migrations.AlterField(
            model_name='periodovacacional',
            name='funcionario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periodos_vacacionales', to='usuarios.funcionario', verbose_name='Funcionario'),
        ),
    ]
