# Generated by Django 5.2 on 2025-04-23 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacaciones', '0004_alter_periodovacacional_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='periodovacacional',
            name='dias_totales_periodo',
            field=models.IntegerField(editable=False, verbose_name='Días totales del periodo'),
        ),
    ]
