# Generated by Django 5.2 on 2025-04-23 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacaciones', '0005_alter_periodovacacional_dias_totales_periodo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='periodovacacional',
            name='dias_pendientes_periodo',
            field=models.IntegerField(default=0, editable=False, verbose_name='Días pendientes del periodo'),
        ),
        migrations.AlterField(
            model_name='periodovacacional',
            name='dias_totales_periodo',
            field=models.IntegerField(default=0, editable=False, verbose_name='Días totales del periodo'),
        ),
    ]
