# Generated by Django 5.2 on 2025-05-06 03:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_remove_customuser_first_name_and_more'),
        ('vacaciones', '0006_alter_periodovacacional_dias_pendientes_periodo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reintegrovacaciones',
            name='funcionario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reintegros_vacaciones', to='usuarios.funcionario'),
        ),
    ]
