# Generated by Django 5.2 on 2025-05-21 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacaciones', '0007_alter_reintegrovacaciones_funcionario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitudvacaciones',
            name='tipo_dias_solicitados',
        ),
    ]
