# Generated by Django 5.2 on 2025-05-28 16:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacaciones', '0008_remove_solicitudvacaciones_tipo_dias_solicitados'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudvacaciones',
            name='fecha_solicitud',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fecha de solicitud'),
            preserve_default=False,
        ),
    ]
