# Generated by Django 5.2 on 2025-06-25 00:05

from django.db import migrations
from datetime import date


def calcular_fecha_pago_para_registros_existentes(apps, schema_editor):
    """
    Calcula la fecha de pago para todos los registros existentes basándose en
    la fecha de elaboración y el tipo de funcionario.
    """
    SolicitudVacaciones = apps.get_model('vacaciones', 'SolicitudVacaciones')
    
    for solicitud in SolicitudVacaciones.objects.all():
        fecha_elaboracion = solicitud.fecha_elaboracion
        estamento = solicitud.funcionario.estamento.nombre.lower()
        decreto = (solicitud.funcionario.decreto_resolucion or '').strip()
        
        if estamento == 'docente':
            # Docentes: pago mensual el día 30
            # Si la solicitud se hace antes del día 10, el pago es el 30 del mes actual
            # Si se hace después del día 10, el pago es el 30 del mes siguiente
            if fecha_elaboracion.day <= 10:
                # Pago el 30 del mes actual
                if fecha_elaboracion.month == 12:
                    # Diciembre: pago el 30 de diciembre
                    fecha_pago = date(fecha_elaboracion.year, 12, 30)
                else:
                    fecha_pago = date(fecha_elaboracion.year, fecha_elaboracion.month, 30)
            else:
                # Pago el 30 del mes siguiente
                if fecha_elaboracion.month == 12:
                    # Diciembre: pago el 30 de enero del año siguiente
                    fecha_pago = date(fecha_elaboracion.year + 1, 1, 30)
                else:
                    fecha_pago = date(fecha_elaboracion.year, fecha_elaboracion.month + 1, 30)
        else:
            # Administrativos y trabajadores oficiales: pago quincenal (15 y 30)
            if fecha_elaboracion.day <= 3:
                # Pago el 15 del mes actual
                fecha_pago = date(fecha_elaboracion.year, fecha_elaboracion.month, 15)
            elif fecha_elaboracion.day <= 18:
                # Pago el 30 del mes actual
                fecha_pago = date(fecha_elaboracion.year, fecha_elaboracion.month, 30)
            else:
                # Pago el 15 del mes siguiente
                if fecha_elaboracion.month == 12:
                    # Diciembre: pago el 15 de enero del año siguiente
                    fecha_pago = date(fecha_elaboracion.year + 1, 1, 15)
                else:
                    fecha_pago = date(fecha_elaboracion.year, fecha_elaboracion.month + 1, 15)
        
        # Actualizar la solicitud
        solicitud.fecha_pago = fecha_pago
        solicitud.mes_pago = fecha_pago.month
        solicitud.anio_pago = fecha_pago.year
        solicitud.save()


def reverse_calcular_fecha_pago(apps, schema_editor):
    """
    Función de reversión: establece fecha_pago como None
    """
    SolicitudVacaciones = apps.get_model('vacaciones', 'SolicitudVacaciones')
    SolicitudVacaciones.objects.all().update(fecha_pago=None)


class Migration(migrations.Migration):

    dependencies = [
        ('vacaciones', '0009_solicitudvacaciones_fecha_solicitud'),
    ]

    operations = [
        migrations.RunPython(
            calcular_fecha_pago_para_registros_existentes,
            reverse_calcular_fecha_pago
        ),
    ]
