# Generated by Django 5.2 on 2025-06-25 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacaciones', '0010_populate_fecha_pago'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitudvacaciones',
            name='quincena_pago',
        ),
        migrations.AddField(
            model_name='solicitudvacaciones',
            name='fecha_pago',
            field=models.DateField(blank=True, help_text='Fecha automática calculada según el calendario de pagos', null=True, verbose_name='Fecha de pago'),
        ),
    ]
