# Generated by Django 5.2 on 2025-06-25 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacaciones', '0011_remove_solicitudvacaciones_quincena_pago_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitudvacaciones',
            name='anio_pago',
        ),
        migrations.RemoveField(
            model_name='solicitudvacaciones',
            name='mes_pago',
        ),
    ]
