# Generated by Django 5.2 on 2025-07-15 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacaciones', '0012_remove_solicitudvacaciones_anio_pago_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reintegrovacaciones',
            old_name='fecha_elaboracion',
            new_name='fecha_solicitud',
        ),
        migrations.RenameField(
            model_name='solicitudvacaciones',
            old_name='disfrute_dias_pendientes',
            new_name='tiene_dias_pendientes',
        ),
        migrations.RemoveField(
            model_name='solicitudvacaciones',
            name='fecha_elaboracion',
        ),
        migrations.AlterField(
            model_name='solicitudvacaciones',
            name='fecha_pago',
            field=models.DateField(blank=True, help_text='Fecha calculada automáticamente según el calendario de pagos', null=True, verbose_name='Fecha de pago'),
        ),
    ]
