# Generated by Django 5.2 on 2025-07-17 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacaciones', '0013_rename_fecha_elaboracion_reintegrovacaciones_fecha_solicitud_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudvacaciones',
            name='fecha_solicitud',
            field=models.DateField(verbose_name='Fecha de solicitud'),
        ),
    ]
