# Generated by Django 5.2 on 2025-10-17 05:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacaciones', '0014_alter_solicitudvacaciones_fecha_solicitud'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AprobacionEtapa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etapa', models.CharField(choices=[('JEFE', 'Jefe Inmediato'), ('COORD', 'Coordinación Administrativa'), ('RRHH', 'División de Recursos Humanos')], max_length=5)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobada', 'Aprobada'), ('devuelta', 'Devuelta'), ('rechazada', 'Rechazada'), ('autorizada', 'Autorizada')], default='pendiente', max_length=10)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aprobaciones', to='vacaciones.solicitudvacaciones')),
            ],
            options={
                'verbose_name': 'Aprobación por etapa',
                'verbose_name_plural': 'Aprobaciones por etapa',
                'unique_together': {('solicitud', 'etapa')},
            },
        ),
    ]
