# Generated by Django 5.2 on 2025-10-22 04:47

import django.db.models.deletion
import vacaciones.utils
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('usuarios', '0006_funcionario_jefe_inmediato'),
        ('vacaciones', '0015_aprobacionetapa'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='aprobacionetapa',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='aprobacionetapa',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='aprobacionetapa',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reintegrovacaciones',
            name='creada_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reintegros_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AddField(
            model_name='solicitudvacaciones',
            name='creada_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes_creadas', to=settings.AUTH_USER_MODEL, verbose_name='Creada por'),
        ),
        migrations.AlterField(
            model_name='reintegrovacaciones',
            name='funcionario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reintegros_vacaciones', to='usuarios.funcionario'),
        ),
        migrations.AlterField(
            model_name='solicitudvacaciones',
            name='fecha_solicitud',
            field=models.DateField(default=vacaciones.utils.get_current_date_colombia, verbose_name='Fecha de solicitud'),
        ),
        migrations.AddIndex(
            model_name='aprobacionetapa',
            index=models.Index(fields=['content_type', 'object_id'], name='vacaciones__content_344240_idx'),
        ),
        migrations.AddConstraint(
            model_name='aprobacionetapa',
            constraint=models.UniqueConstraint(fields=('content_type', 'object_id', 'etapa'), name='uniq_aprobacion_content_object_etapa'),
        ),
    ]
