# Generated by Django 5.2 on 2025-10-22 05:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacaciones', '0018_tighten_gfk_non_null'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aprobacionetapa',
            name='solicitud',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aprobaciones', to='vacaciones.solicitudvacaciones'),
        ),
    ]
