# Generated by Django 5.2 on 2025-10-23 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacaciones', '0019_alter_aprobacionetapa_solicitud'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='solicitudvacaciones',
            options={'verbose_name': 'Solicitud de vacaciones', 'verbose_name_plural': 'Solicitudes de vacaciones'},
        ),
        migrations.RemoveField(
            model_name='reintegrovacaciones',
            name='estado_solicitud',
        ),
        migrations.RemoveField(
            model_name='solicitudvacaciones',
            name='estado_solicitud',
        ),
        migrations.AddField(
            model_name='reintegrovacaciones',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('en_revision', 'En revisión'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado'), ('cancelado', 'Cancelado')], default='BORRADOR', max_length=20),
        ),
        migrations.AddField(
            model_name='solicitudvacaciones',
            name='estado',
            field=models.CharField(choices=[('BORRADOR', 'Borrador'), ('PEND_JEFE', 'Pendiente Jefe'), ('PEND_COORD', 'Pendiente Coordinación'), ('PEND_RRHH', 'Pendiente RRHH'), ('AUTORIZADA', 'Autorizada'), ('RECHAZADA', 'Rechazada'), ('DEVUELTA', 'Devuelta')], default='BORRADOR', max_length=20),
        ),
    ]
