# Generated by Django 5.2 on 2025-10-23 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacaciones', '0021_map_old_reintegro_states'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reintegrovacaciones',
            options={'verbose_name': 'Reintegro de vacaciones', 'verbose_name_plural': 'Reintegros de vacaciones'},
        ),
        migrations.AlterField(
            model_name='reintegrovacaciones',
            name='estado',
            field=models.CharField(choices=[('BORRADOR', 'Borrador'), ('PEND_JEFE', 'Pendiente Jefe'), ('PEND_COORD', 'Pendiente Coordinación'), ('PEND_RRHH', 'Pendiente RRHH'), ('AUTORIZADA', 'Autorizada'), ('RECHAZADA', 'Rechazada'), ('DEVUELTA', 'Devuelta')], default='BORRADOR', max_length=20),
        ),
    ]
