# Generated by Django 5.2 on 2025-11-09 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacaciones', '0024_update_estado_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reintegrovacaciones',
            name='estado_solicitud',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('en_revision', 'En revisión'), ('aprobado', 'Aprobada'), ('rechazado', 'Rechazada'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20),
        ),
    ]
