# Generated by Django 5.2 on 2025-11-10 04:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_funcionario_jefe_inmediato'),
        ('vacaciones', '0025_alter_reintegrovacaciones_estado_solicitud'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reintegrovacaciones',
            name='dias_disfrutados_calendario',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reintegrovacaciones',
            name='dias_disfrutados_habiles',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reintegrovacaciones',
            name='dias_pendientes_calendario',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reintegrovacaciones',
            name='dias_pendientes_habiles',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reintegrovacaciones',
            name='es_reintegro_anticipado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reintegrovacaciones',
            name='firmado_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reintegrovacaciones',
            name='firmado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reintegros_firmados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reintegrovacaciones',
            name='periodo_correspondiente_desde',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reintegrovacaciones',
            name='periodo_correspondiente_hasta',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reintegrovacaciones',
            name='dias_disfrutados',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='reintegrovacaciones',
            name='dias_pendientes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='reintegrovacaciones',
            name='estado_solicitud',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('en_revision', 'En revisión'), ('devuelta', 'Devuelta'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado'), ('cancelado', 'Cancelado'), ('completado', 'Completado')], default='pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='reintegrovacaciones',
            name='motivo_reintegro',
            field=models.CharField(choices=[('finalizacion_normal', 'Finalización normal del periodo'), ('suspension_anticipada', 'Suspensión anticipada por necesidad del servicio')], max_length=50),
        ),
        migrations.AlterField(
            model_name='reintegrovacaciones',
            name='tipo_dias_disfrutados',
            field=models.CharField(choices=[('H', 'Hábiles'), ('C', 'Calendario'), ('HC', 'Hábiles y Calendario'), ('N/A', 'No aplica')], default='N/A', max_length=3),
        ),
        migrations.AlterField(
            model_name='reintegrovacaciones',
            name='tipo_dias_pendientes',
            field=models.CharField(choices=[('H', 'Hábiles'), ('C', 'Calendario'), ('HC', 'Hábiles y Calendario'), ('N/A', 'No aplica')], default='N/A', max_length=3),
        ),
        migrations.AddConstraint(
            model_name='reintegrovacaciones',
            constraint=models.UniqueConstraint(condition=models.Q(('estado_solicitud__in', ['pendiente', 'en_revision', 'devuelta', 'aprobado'])), fields=('solicitud_vacaciones',), name='uniq_reintegro_activo_por_solicitud'),
        ),
    ]
