# Generated by Django 5.2 on 2025-11-12 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacaciones', '0026_reintegrovacaciones_dias_disfrutados_calendario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudvacaciones',
            name='es_por_reintegro_anticipado',
            field=models.BooleanField(default=False, help_text='Marque esta opción si la solicitud se realiza debido a un reintegro anticipado por necesidad del servicio', verbose_name='Solicitud por reintegro anticipado'),
        ),
        migrations.AlterField(
            model_name='reintegrovacaciones',
            name='motivo_reintegro',
            field=models.CharField(choices=[('finalizacion_normal', 'Finalización del periodo de vacaciones'), ('suspension_anticipada', 'Suspensión anticipada por necesidad del servicio')], max_length=50),
        ),
    ]
