# Generated by Django 5.2 on 2025-11-14 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacaciones', '0028_update_authorized_states'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reintegrovacaciones',
            name='estado_solicitud',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('en_revision', 'En revisión'), ('devuelta', 'Devuelta'), ('aprobado', 'Aprobado'), ('autorizada', 'Autorizada'), ('rechazado', 'Rechazado'), ('cancelado', 'Cancelado'), ('completado', 'Completado')], default='pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='solicitudvacaciones',
            name='estado_solicitud',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('en_revision', 'En revisión'), ('aprobado', 'Aprobada'), ('autorizada', 'Autorizada'), ('rechazado', 'Rechazada'), ('devuelta', 'Devuelta'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20),
        ),
    ]
