# Generated by Django 5.2 on 2025-04-16 06:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0004_alter_customuser_options_alter_funcionario_options'),
        ('vacaciones', '0002_alter_diaspendientesvacaciones_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asunto', models.CharField(max_length=150, verbose_name='Asunto')),
                ('mensaje', models.TextField(verbose_name='Mensaje')),
                ('fecha_hora_envio', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y hora de envío')),
                ('enviado', models.BooleanField(default=False, verbose_name='¿Enviado?')),
                ('tipo_notificacion', models.CharField(choices=[('solicitud', 'Solicitud'), ('reintegro', 'Reintegro')], max_length=20, verbose_name='Tipo de notificación')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones_recibidas', to='usuarios.funcionario', verbose_name='Funcionario destinatario')),
                ('funcionario_cc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notificaciones_copia', to='usuarios.funcionario', verbose_name='Funcionario CC')),
                ('reintegro_vacaciones', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vacaciones.reintegrovacaciones', verbose_name='Reintegro relacionado')),
                ('solicitud_vacaciones', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vacaciones.solicitudvacaciones', verbose_name='Solicitud relacionada')),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
            },
        ),
    ]
