# Generated by Django 5.2 on 2025-04-05 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
        ('vacaciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asunto', models.CharField(max_length=150)),
                ('mensaje', models.TextField()),
                ('fecha_hora_envio', models.DateTimeField(auto_now_add=True)),
                ('enviado', models.BooleanField(default=False)),
                ('tipo_notificacion', models.CharField(choices=[('solicitud', 'Solicitud'), ('reintegro', 'Reintegro')], max_length=20)),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.funcionario')),
                ('reintegro_vacaciones', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vacaciones.reintegrovacaciones')),
                ('solicitud_vacaciones', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vacaciones.solicitudvacaciones')),
            ],
        ),
    ]
