# Generated by Django 5.2 on 2025-04-17 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estamento',
            options={'verbose_name': 'Estamento', 'verbose_name_plural': 'Estamentos'},
        ),
        migrations.AlterModelOptions(
            name='facultaddependencia',
            options={'verbose_name': 'Facultad - Dependencia', 'verbose_name_plural': 'Facultades - Dependencias'},
        ),
        migrations.AlterModelOptions(
            name='sede',
            options={'verbose_name': 'Sede', 'verbose_name_plural': 'Sedes'},
        ),
    ]
