# Generated by Django 5.2 on 2025-04-05 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('numero_identificacion', models.CharField(max_length=50, unique=True)),
                ('correo_electronico', models.EmailField(max_length=254, unique=True)),
                ('telefono', models.CharField(max_length=20)),
                ('fecha_ingreso_universidad', models.DateField()),
                ('estamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='funcionarios_estamento', to='core.catalogo')),
                ('facultad_dependencia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='funcionarios_facultad_dependencia', to='core.catalogo')),
                ('sede', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.sede')),
            ],
        ),
    ]
