# Generated by Django 5.2 on 2025-04-08 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='decreto_resolucion',
            field=models.CharField(blank=True, help_text="Código de resolución para docentes ('1279' o '115')", max_length=10, null=True),
        ),
    ]
