# Generated by Django 5.2 on 2025-10-22 04:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_remove_customuser_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='jefe_inmediato',
            field=models.ForeignKey(blank=True, help_text='Funcionario que actúa como Jefe Inmediato', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinados', to='usuarios.funcionario'),
        ),
    ]
